from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

## Generated by secrets.token_hex(16) module
SECRET_KEY = "fd73aa502bb6bb9bfd3e7657ebc0a550"
app.config['SECRET_KEY'] = SECRET_KEY
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///site.db"
db = SQLAlchemy(app)

from webui import routes
